apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps
  # - ../../../infrastructure

labels:
- includeSelectors: true
  pairs:
    environment: latest

# Create a single resource for this environment that can be used by replacements.
#
configMapGenerator:
  - name: flux-env
    literals:
      - fluxEnv=latest
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

patches:
  - target:
      kind: OCIRepository
    patch: |-
      - op: add
        path: /spec/ref
        value: "semverFilter: \".*-latest.*\""