apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../../apps
  - ../../../infrastructure

labels:
- includeSelectors: true
  pairs:
    environment: stable

nameSuffix: -stable
